### ISSUE TITLE
Account and authentication endpoints

### ISSUE THREAD

**Issue by ChurchOfTheSubgenius** [commune-os/commune-rs#48]
To start working towards meeting API parity with the golang server, we should start out by implementing the account and authentication API endpoints. Please refer to the `account` table in issue #43.

**Comment by avdb13** [comment]
Account routes should probably pay attention to https://github.com/matrix-org/matrix-spec-proposals/pull/2828 so that future compatibility with Conduit (which I'm pretty sure already performs username validity checks) isn't broken.

On the other hand, I wonder whether the password reset route only requires the old password. The API just falls back on UIAA which requires a user identifier but `/whoami` can translate the access token to a username whenever necessary.
Refer: https://docs.ruma.io/ruma_client_api/uiaa/enum.UserIdentifier.html

**Comment by erlend-sh** [comment]
Future compatibility with Conduit is a non-concern at this stage. We build to be compatible with Synapse first, and make changes in the future if necessary for compatibility with Conduit.

Trying to preempt future requirements now will require much more time and work as opposed to being adaptable to changing requirements as they become practical reality.

**Comment by ChurchOfTheSubgenius** [comment]
For now, let's do what the golang code does. Once the API parity list on #43 reaches fully green, then we can think of enhancements and optimizations.

**Comment by avdb13** [comment]
https://github.com/commune-os/commune-rs/pull/51 dealed with the account endpoints.

**Comment by avdb13** [comment]
Closed in favor of https://github.com/commune-os/commune-rs/issues/53.
